export const products = [
    {
        id: 1,
        name: 'Product 1',
        price: 29.99,
        image: '/assets/images/product1.jpg',
        description: 'This is a great product.',
        featured: true,
    },
    {
        id: 2,
        name: 'Product 2',
        price: 39.99,
        image: '/assets/images/product2.jpg',
        description: 'This product is even better.',
        featured: true,
    },
    {
        id: 3,
        name: 'Product 3',
        price: 49.99,
        image: '/assets/images/product3.jpg',
        description: 'You will love this product.',
        featured: true,
    },
    {
        id: 4,
        name: 'Product 4',
        price: 59.99,
        image: '/assets/images/product4.jpg',
        description: 'This is the best product we offer.',
        featured: true,
    },
    {
        id: 5,
        name: 'Product 5',
        price: 69.99,
        image: '/assets/images/product5.jpg',
        description: 'An amazing product that you can\'t miss.',
        featured: true,
    },
    {
        id: 6,
        name: 'Product 6',
        price: 79.99,
        image: '/assets/images/product6.jpg',
        description: 'A product that combines quality and value.',
        featured: true,
    },
    {
        id: 7,
        name: 'Product 7',
        price: 89.99,
        image: '/assets/images/product7.jpg',
        description: 'A premium product for discerning customers.',
    },
    {
        id: 8,
        name: 'Product 8',
        price: 99.99,
        image: '/assets/images/product8.jpg',
        description: 'An exclusive product with limited availability.',
    },
    {
        id: 9,
        name: 'Product 9',
        price: 109.99,
        image: '/assets/images/product9.jpg',
        description: 'A product that sets new standards.',
    },
    {
        id: 10,
        name: 'Product 10',
        price: 119.99,
        image: '/assets/images/product10.jpg',
        description: 'The ultimate product for your needs.',
    },
    {
        id: 11,
        name: 'Product 11',
        price: 129.99,
        image: '/assets/images/product11.jpg',
        description: 'A product that combines innovation and style.',
    },
    
]